

name: 'tsm_dataanalyse'
version: '1.0.0'
profile: 'tsm_dataanalyse'
flags:
  send_anonymous_usage_stats: false # stopper datasending
clean-targets:
  - "target"
  - "dbt_packages"



model-paths: ["models"]
macro-paths: ["macros"]



models:
  tsm_dataanalyse:

    +materialized: view

    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
    exposed:
      +schema: exposed
    exposed_access_controlled:
      +schema: exposed
