tsm_dataanalyse:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: tsm-prod-1dab
      dataset: dbt
      threads: 1
      location: europe-north1
    dev:
      type: bigquery
      method: oauth
      project: tsm-dev-6602
      dataset: dbt
      threads: 1
      location: europe-north1
