tsm_dataanalyse:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_DATABASE') }}"
      dataset: dbt
      threads: 1
      location: "{{ env_var('DBT_LOCATION') }}"
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_DATABASE') }}"
      dataset: dbt
      threads: 1
      location: "{{ env_var('DBT_LOCATION') }}"
