[project]
name = "tsm-dataanalyse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.11, <1.12",
    "dbt-core>=1.11.8, <1.12",
    "google-cloud-bigquery>=3.42.1, <4.0",
    "plotly>=6.8.0",
    "polars>=1.42.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
lint = [
    "pre-commit>=4.6.0",
]
