SELECT
  sykmelding_id as id,
  fom,
  tom,
  JSON_EXTRACT_SCALAR(validation, '$.status') AS last_status,
  JSON_EXTRACT_ARRAY('sykmelding', '$.aktivitet') AS aktivitet,
  {{ extract_json_fields('sykmelding',
    [ {'key': 'type', 'name': 'sm_type'},
    {'key':'prognose.arbeid', 'name': 'prognose_arbeid' },
    {'key':'prognose.hensynArbeidsplassen', 'name': 'prognose_hensynArbeidsplassen' },
    {'key':'prognose.arbeidsforEtterPeriode', 'name': 'arbeidsforEtterPeriode' },
    {'key':'metadata.mottattDato', 'name': 'mottattDato' },
    {'key':'metadata.avsenderSystem.navn', 'name': 'avsenderSystem_navn' },
    {'key':'metadata.avsenderSystem.versjon', 'name': 'avsenderSystem_versjon' },
    {'key':'metadata.regelsettVersjon', 'name': 'regelsettVersjon' },
    {'key':'metadata.behandletTidspunkt', 'name': 'behandletTidspunkt' },
    {'key':'sykmelder.helsepersonellKategori', 'name': 'helsepersonellKategori' },
    {'key':'arbeidsgiver.navn', 'name': 'arbeidsgiver_navn' },
    {'key':'arbeidsgiver.type', 'name': 'arbeidsgiver_type' },
    {'key':'tilbakedatering', 'name': 'tilbakedatering' },
    {'key':'medisinskVurdering.hovedDiagnose.kode', 'name': 'hoveddiagnose_kode' },
    {'key':'medisinskVurdering.hovedDiagnose.system', 'name': 'hoveddiagnose_system' },
    {'key':'medisinskVurdering.syketilfelletStartDato', 'name': 'syketilfelletStartDato' },
    ])}},
  JSON_EXTRACT_ARRAY('sykmelding', '$.medisinskVurdering.biDiagnoser') AS bidiagnoser
FROM
  {{ source('tsm_dataset_dev', 'regulus_maximus')}}
